language: node_js
node_js:
  - 0.8
  - 0.10
before_script:
  mkdir -p shippable/codecoverage shippable/testresults
script:
  - npm test  && npm run-script coveralls 
after_script: 
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -u tdd 
  - ./node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/
